-- Your SQL goes here

ALTER TABLE rewards
ADD COLUMN icon TEXT NOT NULL DEFAULT 'gCoffee';
ALTER TABLE rewards ALTER COLUMN icon DROP DEFAULT;

ALTER TABLE tasks
ADD COLUMN icon TEXT NOT NULL DEFAULT 'rWriting';
ALTER TABLE tasks ALTER COLUMN icon DROP DEFAULT;