version: "3.8"
services:
  web:
    image: olsons10/bspts
    env_file: 
      - compose.env
    ports:
      - "3030:3030"
  db:
    image: postgres
    env_file: 
      - compose.env
    volumes:
      - db_data:/var/lib/postgresql/data
volumes:
  db_data: