[env]
CARGO_MAKE_EXTEND_WORKSPACE_MAKEFILE = true

[config]
default_to_workspace = false

[tasks.data]
command = "cargo"
args = ["build", "-p", "data"]
watch = { watch = ["data"] }

[tasks.front]
cwd = "frontend"
command = "wasm-pack"
args = ["build", "--dev", "--target", "web", "--out-name", "bspts", "--out-dir", "../site/scripts"]
watch = { watch = ["frontend"] }

[tasks.run]
command = "cargo"
args = ["run", "-p", "backend"]
watch = { watch = ["backend"] }

[tasks.test-db]
script = "docker run --rm --name bspts_db_container -p 5433:5432 -d bspts_test_db"

[tasks.stop-db]
script = "docker stop bspts_db_container"