[env]
CARGO_MAKE_EXTEND_WORKSPACE_MAKEFILE = true

[config]
default_to_workspace = false

[tasks.data]
command = "cargo"
args = ["build", "-p", "data"]
watch = { watch = ["data"] }

[tasks.front]
command = "wasm-pack"
args = ["build", "frontend", "--dev", "--target", "web", "--out-name", "bspts", "--out-dir", "../site/scripts"]
watch = { watch = ["frontend"] }

[tasks.run]
command = "cargo"
args = ["run", "-p", "backend"]
watch = { watch = ["backend"] }

# Starts a new datadase container listening to 5433
[tasks.test-db]
script = """
    docker run --rm \
    --name bspts_db_container \
    -e POSTGRES_DB=bspts_db \
    -e POSTGRES_PASSWORD=pw \
    -p 5433:5432 \
    -d postgres
"""

# Stops the container
[tasks.stop-db]
script = "docker stop bspts_db_container"

[tasks.build-app]
script = "docker build . -t olsons10/bspts"

[tasks.run-contained]
script = [
    "docker-compose up"
]